location: .gitman
sources:
  - name: mrs_gazebo_common_resources
    type: git
    repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive --depth 1
  - name: mrs_simulation
    type: git
    repo: https://github.com/ctu-mrs/mrs_simulation.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive --depth 1
  - name: px4_firmware
    type: git
    repo: https://github.com/ctu-mrs/px4_firmware.git
    sparse_paths:
      -
    rev: 1.11.2
    link:
    scripts:
      - git submodule update --init --recursive --depth 1
sources_locked:
  - name: mrs_gazebo_common_resources
    type: git
    repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    sparse_paths:
      -
    rev: 9047f7aa0e567b382a5316f77179cb8d0dfbaceb
    link:
    scripts:
      - git submodule update --init --recursive --depth 1
  - name: mrs_simulation
    type: git
    repo: https://github.com/ctu-mrs/mrs_simulation.git
    sparse_paths:
      -
    rev: 88fbf9ad20359b687df95df4e22b7ff3d31f91dd
    link:
    scripts:
      - git submodule update --init --recursive --depth 1
  - name: px4_firmware
    type: git
    repo: https://github.com/ctu-mrs/px4_firmware.git
    sparse_paths:
      -
    rev: a50b6c262d86c3259e7d4ba36b29e47a7276964e
    link:
    scripts:
      - git submodule update --init --recursive --depth 1
default_group: ''
groups:
  -
