location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_gazebo_common_resources
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_simulation
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1.11.2
    type: git
    sparse_paths:
      -
    link: ros_packages/px4_firmware
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: 071e4757787db47ea226d8dd531786822b802f5c
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_gazebo_common_resources
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: d7d13b8762159b06e898dedbf8405b13deddee54
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_simulation
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 32baaeac23205107944733dd33a8a73ee8ba8274
    type: git
    sparse_paths:
      -
    link: ros_packages/px4_firmware
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
default_group: ''
groups:
  -
