location: .gitman
sources:
- name: mrs_gazebo_common_resources
  type: git
  repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_gazebo_common_resources
  scripts:
  - git submodule update --init --recursive --depth 1
- name: mrs_simulation
  type: git
  repo: https://github.com/ctu-mrs/mrs_simulation.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_simulation
  scripts:
  - git submodule update --init --recursive --depth 1
- name: px4_firmware
  type: git
  repo: https://github.com/ctu-mrs/px4_firmware.git
  sparse_paths:
  -
  rev: v1.10.1
  link: ros_packages/px4_firmware
  scripts:
  - git submodule update --init --recursive --depth 1
sources_locked:
- name: mrs_gazebo_common_resources
  type: git
  repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
  sparse_paths:
  -
  rev: 6f709769b017817d9202daca1ff71987e0b64bd6
  link: ros_packages/mrs_gazebo_common_resources
  scripts:
  - git submodule update --init --recursive --depth 1
- name: mrs_simulation
  type: git
  repo: https://github.com/ctu-mrs/mrs_simulation.git
  sparse_paths:
  -
  rev: 0423f0a85712768c2c1c5ec1836ebcb125ce7cf3
  link: ros_packages/mrs_simulation
  scripts:
  - git submodule update --init --recursive --depth 1
- name: px4_firmware
  type: git
  repo: https://github.com/ctu-mrs/px4_firmware.git
  sparse_paths:
  -
  rev: 7c132941e05968b2d8170d0f16d6410bc8ae84f6
  link: ros_packages/px4_firmware
  scripts:
  - git submodule update --init --recursive --depth 1
groups: []
