location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_gazebo_common_resources
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_simulation
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1.11.2
    type: git
    sparse_paths:
      -
    link: ros_packages/px4_firmware
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: ca03d15afdba91a5e385ff75c4afb235bc7d7267
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_gazebo_common_resources
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: d4fb6c73adb80b85662b301192622a27cd834e94
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_simulation
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 162b68d81d335ea4b69e3265b2b534675d387bf3
    type: git
    sparse_paths:
      -
    link: ros_packages/px4_firmware
    links:
      -
    scripts:
      - git submodule update --init --recursive --depth 1
default_group: ''
groups:
  -
