location: .gitman
sources:
- name: mrs_gazebo_common_resources
  type: git
  repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_gazebo_common_resources
  scripts:
  - git submodule update --init --recursive --depth 1
- name: mrs_simulation
  type: git
  repo: https://github.com/ctu-mrs/mrs_simulation.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_simulation
  scripts:
  - git submodule update --init --recursive --depth 1
- name: px4_firmware
  type: git
  repo: https://github.com/ctu-mrs/px4_firmware.git
  sparse_paths:
  -
  rev: v1.10.1
  link: ros_packages/px4_firmware
  scripts:
  - git submodule update --init --recursive --depth 1
sources_locked:
- name: mrs_gazebo_common_resources
  type: git
  repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
  sparse_paths:
  -
  rev: f8ce297b02414baa26eb1088cad87aa2fdea56da
  link: ros_packages/mrs_gazebo_common_resources
  scripts:
  - git submodule update --init --recursive --depth 1
- name: mrs_simulation
  type: git
  repo: https://github.com/ctu-mrs/mrs_simulation.git
  sparse_paths:
  -
  rev: c7deb24ff80d684d90f98fa2d8dfef91e7df292a
  link: ros_packages/mrs_simulation
  scripts:
  - git submodule update --init --recursive --depth 1
- name: px4_firmware
  type: git
  repo: https://github.com/ctu-mrs/px4_firmware.git
  sparse_paths:
  -
  rev: 5f756e495caddfaa597fa5cc785b5c1f0aeeb436
  link: ros_packages/px4_firmware
  scripts:
  - git submodule update --init --recursive --depth 1
groups: []
