location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1.11.2
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive --depth 1
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: 7812c0032c3ab9ad25d3b0eeba9c8f34900bf317
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: 04c8316f9c0f81dcba188d123a337d78e9096e21
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: a50b6c262d86c3259e7d4ba36b29e47a7276964e
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive --depth 1
default_group: ''
groups:
  -
