location: .gitman
sources:
- name: mrs_gazebo_common_resources
  type: git
  repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_gazebo_common_resources
  scripts:
  - git submodule update --init --recursive --depth 1
- name: mrs_simulation
  type: git
  repo: https://github.com/ctu-mrs/mrs_simulation.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_simulation
  scripts:
  - git submodule update --init --recursive --depth 1
- name: px4_firmware
  type: git
  repo: https://github.com/ctu-mrs/px4_firmware.git
  sparse_paths:
  -
  rev: v1.11.1
  link: ros_packages/px4_firmware
  scripts:
  - git submodule update --init --recursive --depth 1
sources_locked:
- name: mrs_gazebo_common_resources
  type: git
  repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
  sparse_paths:
  -
  rev: 1ef6f264075b365091f505b40c07519dd992f191
  link: ros_packages/mrs_gazebo_common_resources
  scripts:
  - git submodule update --init --recursive --depth 1
- name: mrs_simulation
  type: git
  repo: https://github.com/ctu-mrs/mrs_simulation.git
  sparse_paths:
  -
  rev: ed7fbf274312eae8172541db3fea0a23f9bc8755
  link: ros_packages/mrs_simulation
  scripts:
  - git submodule update --init --recursive --depth 1
- name: px4_firmware
  type: git
  repo: https://github.com/ctu-mrs/px4_firmware.git
  sparse_paths:
  -
  rev: 3d43f8831a0d59d724e3f73db49fbea24e7668bd
  link: ros_packages/px4_firmware
  scripts:
  - git submodule update --init --recursive --depth 1
groups: []
