location: .gitman
sources:
  - name: mrs_gazebo_common_resources
    type: git
    repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive --depth 1
  - name: mrs_simulation
    type: git
    repo: https://github.com/ctu-mrs/mrs_simulation.git
    sparse_paths:
      -
    rev: master
    link: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive --depth 1
  - name: px4_firmware
    type: git
    repo: https://github.com/ctu-mrs/px4_firmware.git
    sparse_paths:
      -
    rev: v1.11.2
    link: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive --depth 1
sources_locked:
  - name: mrs_gazebo_common_resources
    type: git
    repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    sparse_paths:
      -
    rev: 367830b05fb0c9d3ebad8b31066f075ca3dba4ae
    link: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive --depth 1
  - name: mrs_simulation
    type: git
    repo: https://github.com/ctu-mrs/mrs_simulation.git
    sparse_paths:
      -
    rev: f2c968f943792f58bded3a24e8b387c024cda415
    link: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive --depth 1
  - name: px4_firmware
    type: git
    repo: https://github.com/ctu-mrs/px4_firmware.git
    sparse_paths:
      -
    rev: 1f291f851b31e01da78ed4474048976b74cbe8df
    link: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive --depth 1
default_group: ''
groups:
  -
