location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: 1.11.2
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive --depth 1
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_gazebo_common_resources.git
    name: mrs_gazebo_common_resources
    rev: bfbc4d2752e11ec43e2e4504a0b901594397eb51
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_gazebo_common_resources
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/mrs_simulation.git
    name: mrs_simulation
    rev: 20b91aa1b8948d628e46a73a9be70f51fd003b03
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_simulation
    scripts:
      - git submodule update --init --recursive --depth 1
  - repo: https://github.com/ctu-mrs/px4_firmware.git
    name: px4_firmware
    rev: a50b6c262d86c3259e7d4ba36b29e47a7276964e
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/px4_firmware
    scripts:
      - git submodule update --init --recursive --depth 1
default_group: ''
groups:
  -
